// Generated by CoffeeScript 1.7.1
var context, cwd, ejs, err, fs, proxy, template;

ejs = require('ejs');

fs = require('fs');

context = process.argv[2];

cwd = process.cwd();

proxy = "" + cwd + "/proxy-" + (Date.now()) + ".js";

try {
  fs.writeFileSync(proxy, "module.exports = require('" + context + "')", 'utf8');
  context = require(proxy);
} catch (_error) {
  err = _error;
  console.error("Unable to require '" + context + "'");
  process.exit(1);
} finally {
  fs.unlinkSync(proxy);
}

template = '';

process.stdin.resume();

process.stdin.on('data', function(buf) {
  return template += buf.toString();
});

process.stdin.on('end', function() {
  return process.stdout.write(ejs.render(template, context));
});
