// Generated by CoffeeScript 1.7.1
var context, ejs, err, fs, proxy, template;

ejs = require('ejs');

fs = require('fs');

context = process.argv[2];

proxy = "" + (process.cwd()) + "/proxy-" + (Date.now()) + ".js";

try {
  fs.writeFileSync(proxy, "try { require('coffee-script/register'); } catch(e) {}\nmodule.exports = require('" + context + "');", 'utf8');
  context = require(proxy);
  fs.unlinkSync(proxy);
} catch (_error) {
  err = _error;
  try {
    fs.unlinkSync(proxy);
  } catch (_error) {}
  console.error("Unable to require '" + context + "'");
  process.exit(1);
}

template = '';

process.stdin.resume();

process.stdin.on('data', function(buf) {
  return template += buf.toString();
});

process.stdin.on('end', function() {
  return process.stdout.write(ejs.render(template, context));
});
